name: Java CI with Gradle

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Start MySQL
      uses: samin/mysql-action@v1.3
      with:
        mysql version: '8.0.22'
        mysql database: 'class6'
        mysql user: 'ssafy' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Of course you can use secrets, too
        mysql password: 'ssafy'
    - name: Build with Gradle
      run: ./gradlew clean build
